### ISSUE TITLE
Database format for Realtime Data like IoT data

### ISSUE THREAD

**Issue by ghost** [orbitdb/orbit-db#399] opened 2018-07-09 05:16 UTC
What sort of database type can be created with orbit db when implementing it with IoT data. Also I have been using go-ipfs for all the experiments with IPFS. But I don't find a version of orbit DB with go-ipfs. But implementation with js.ipfs exists. If I install them in the same machine will it still work?

**Comment by RichardLitt** [comment] 2018-07-09 13:24
Duplicate of #400.

**Closed by RichardLitt** 2018-07-09 13:24 UTC
